name: triggering_code

on: 
   push:
        branches:
            - main
        paths:
            - 'cameraSupervision/**'
            - 'demoRedBallCalibration/**'
            - '!**/README.md'

jobs:
    test:
      runs-on: [ubuntu-latest]
      steps:
        - id: file_changes
          if: github.event_name == 'push'
          uses: trilom/file-changes-action@v1.2.3
        - name: files
          if: github.event_name == 'push'
          id: check-modifications
          run: |
            cat $HOME/files.json
            cat $HOME/files_modified.json
            cat $HOME/files_added.json
            echo '${{ steps.file_changes.outputs.files}}'
            echo '${{ steps.file_changes.outputs.files_modified}}'
            echo '${{ steps.file_changes.outputs.files_added}}'
            parsed_list=($(echo '${{ steps.file_changes.outputs.files}}' | tr ',' '\n')) 
            img_list=""
            for i in "${parsed_list[@]}"
            do 
                folder=$(echo $i | awk -F'/' '{print $1}' | tr -d '"' | tr -d '[' | tr -d ']')
                if [[ "$folder" == "cameraSupervision" ]]
                then
                  img_list="$img_list supervise-calib"
                elif [[ "$folder" == "demoRedBallCalibration" ]]
                then
                  img_list="$img_list grasp-the-ball"
                fi
            done
            img_list=${img_list:1}
            img_list_unique=$(echo $img_list | tr ' ' '\n' | sort -u | tr '\n' ' ' )
            echo "Image list: $img_list_unique"
            echo "::set-output name=img_list_unique::$img_list_unique"

        - name: Get Token
          id: get_workflow_token
          uses: tibdex/github-app-token@v1
          with:
            private_key: ${{ secrets.ICUB_TECH_CODE_KEY }}
            app_id: ${{ secrets.ICUB_TECH_CODE_ID }}
            repository: icub-tech-iit/code
            
        - name: Repository dispatch to code
          uses: peter-evans/repository-dispatch@v1
          env:
            GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          with:
            token: ${{ env.GITHUB_APPS_TOKEN }}
            repository: icub-tech-iit/code
            event-type: repository_trigger
            client-payload: '{"type": "repository_trigger", "img_list": "${{ steps.check-modifications.outputs.img_list_unique }}"}'

